// AUTO-GENERATED by @michalsy/aiko-webapp-core
// Do not edit this file directly. Update aikoapp.json instead.

import { NextResponse } from 'next/server'
import { createServerClient } from '@supabase/ssr'
import { cookies } from 'next/headers'

export const dynamic = 'force-dynamic'

const PASSIERSCHEIN_ID = 'access'
const APP_NAME = 'void-stream'

async function createSupabaseServerClient() {
  const cookieStore = await cookies()
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY

  if (!supabaseUrl || !supabaseKey) {
    throw new Error('Missing Supabase environment variables')
  }

  return createServerClient(supabaseUrl, supabaseKey, {
    cookies: {
      getAll() { return cookieStore.getAll() },
      setAll(cookiesToSet) {
        try {
          cookiesToSet.forEach(({ name, value, options }) =>
            cookieStore.set(name, value, options)
          )
        } catch {}
      },
    },
  })
}

export async function GET() {
  try {
    const supabase = await createSupabaseServerClient()
    const { data: { user } } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json({ hasAccess: false, reason: 'not_authenticated', abilities: [] })
    }

    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
    const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY
    if (!supabaseUrl || !serviceKey) {
      return NextResponse.json({ hasAccess: false, reason: 'missing_service_key', abilities: [] })
    }

    const { createClient } = await import('@supabase/supabase-js')
    const adminClient = createClient(supabaseUrl, serviceKey)

    // Fetch ability IDs for THIS APP only (via guild_abilities join)
    const { data: abilities } = await adminClient
      .from('guild_user_abilities')
      .select(`
        ability_id,
        guild_abilities!inner ( id, name, emoji, description )
      `)
      .eq('user_id', user.id)
      .eq('app_name', APP_NAME)

    const abilityIds = (abilities || []).map((a: any) => a.ability_id as string)

    return NextResponse.json({
      hasAccess: abilityIds.includes(PASSIERSCHEIN_ID),
      abilities: abilityIds,
      userId: user.id,
      email: user.email,
      app: APP_NAME,
    })
  } catch (error: any) {
    console.error('[ACCESS] Error:', error)
    return NextResponse.json({ error: error.message, abilities: [] }, { status: 500 })
  }
}
