// AUTO-GENERATED by @michalsy/aiko-webapp-core
// Do not edit this file directly. Update aikoapp.json instead.

import { NextResponse } from 'next/server'

export const dynamic = 'force-dynamic'

const APP_NAME = 'void-stream'
const APP_DISPLAY_NAME = 'Void Stream'
const APP_DESCRIPTION = 'Nerd-grade video streaming platform'
const APP_ABILITIES = [
  {
    "id": "access",
    "name": "Passierschein",
    "emoji": "🎫",
    "description": "Zugang zu Void Stream",
    "is_passierschein": true
  }
] as const

let lastRegister = 0

async function selfRegister() {
  const now = Date.now()
  if (now - lastRegister < 5 * 60 * 1000) return // max alle 5 min
  lastRegister = now

  try {
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
    const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY
    if (!supabaseUrl || !serviceKey) return

    const { createClient } = await import('@supabase/supabase-js')
    const supabase = createClient(supabaseUrl, serviceKey)

    // App registrieren
    await supabase
      .from('guild_apps')
      .upsert({
        name: APP_NAME,
        display_name: APP_DISPLAY_NAME,
        version: process.env.NEXT_PUBLIC_APP_VERSION || '0.0.0',
        description: APP_DESCRIPTION,
        last_seen: new Date().toISOString(),
      }, { onConflict: 'name' })

    // Fähigkeiten registrieren (mit ID)
    for (const ability of APP_ABILITIES) {
      await supabase
        .from('guild_abilities')
        .upsert({
          id: ability.id,
          app_name: APP_NAME,
          name: ability.name,
          emoji: ability.emoji || '⚡',
          description: ability.description || '',
          is_passierschein: (ability as any).is_passierschein ?? false,
        }, { onConflict: 'id,app_name' })
    }

    console.log(`[HEALTH] Registered ${APP_NAME} with ${APP_ABILITIES.length} abilities`)
  } catch (e) {
    console.warn('[HEALTH] Self-register failed:', e)
  }
}

export async function GET() {
  selfRegister() // fire-and-forget

  return NextResponse.json({
    status: 'ok',
    timestamp: new Date().toISOString(),
    app: APP_NAME,
    version: process.env.NEXT_PUBLIC_APP_VERSION || '0.0.0',
  })
}
